language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '10'
before_install:
  - npm install -g yarn
install:
  - yarn install --ignore-scripts
before_script:
  - yarn build
script:
  - yarn commitlint-travis
  - yarn install --production
  - git aliases
  - node lib/remove-config.test
after_success:
  - yarn install --ignore-scripts
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
