language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '6'
  - '8'
before_install:
  - npm install -g yarn
install:
  - yarn install --ignore-scripts
before_script:
  - yarn build
script:
  - if [[ $(node --version) == v4* ]];
    then echo "Running node 4; skipping commitlint.";
    else ./node_modules/.bin/commitlint --from="$TRAVIS_BRANCH" --to="$TRAVIS_COMMIT";
    fi
  - yarn install --production
  - git aliases
  - node lib/remove-config.test
after_success:
  - yarn install --ignore-scripts
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
